[package]
name = "frame"
version = "0.1.0"
edition = "2024"

[dependencies]
fast_image_resize = { version = "5.1.3", features = ["rayon"] }
image = "0.25.6"

photon-rs = { git = "https://github.com/silvia-odwyer/photon", version = "0.3.2" }
wasm-bindgen = "0.2.100"
wgpu = "25.0.0"
